### ISSUE TITLE
Comments and :cursorline

### ISSUE THREAD

**Issue by przmv** [KKPMW/distilled-vim#1]
The current comments line is invisible if `:cursorline` was set:

![image](https://user-images.githubusercontent.com/290451/53485891-768e7b80-3a98-11e9-8d3e-768cbdb47200.png)

**Comment by karoliskoncevicius** [comment]
Thank you for reporting this. I don't personally use CursorLine so didn't catch this.

As far as I see there are a few possible solutions:

1. Leave the background color but set the foreground of "cursorline" to be the same everywhere - either black or white.

It would look something like this:

![option1](https://user-images.githubusercontent.com/7273684/53487740-04686780-3a95-11e9-82ff-eb0a35038758.png)

2. Change the background color so that it's different from the comment color.

And it would look something like this:

![option2](https://user-images.githubusercontent.com/7273684/53487938-983a3380-3a95-11e9-90ab-c349dae369f4.png)

But in this case I would have to introduce a new color into palette.

I assume you are using cursor line. If so - which solution would you prefer? Or maybe you have other suggestions?

**Comment by przmv** [comment]
> Leave the background color but set the foreground of "cursorline" to be the same everywhere - either black or white.

LGTM!

**Comment by karoliskoncevicius** [comment]
It's done: https://github.com/KKPMW/distilled-vim/commit/4276a4517fd56ac84a69cc9210a0085dee4fb743

Thank you for reporting this. Closing now. If something will still not work - please reopen the issue.

**Comment by przmv** [comment]
Looks good! Thank you!
