### ISSUE TITLE
Add highlight for Conceal

### ISSUE THREAD

**Issue by przmv** [KKPMW/distilled-vim#2]
Recently I started creating RMarkdown in vim (with `vim-pandoc-syntax`) and discovered that id uses the default highlighting for Conceal (gray background), so it ain't match the `distilled-vim` scheme. Could you please add some Conceal highlighting?

**Comment by karoliskoncevicius** [comment]
Hello,

For now `conceal` it is linked to `comment`: [#L107](https://github.com/KKPMW/distilled-vim/blob/master/colors/distilled.vim#L107). So it should not be `gray`. Maybe you have a screenshot nearby that you could attach here for reference so that we can be sure we are on the same page?

I am not using conceal myself so am happy to switch it to most anything. Do you have a preferred color for it?

Will investigate it further after installing the `vim-pandoc`.

*PS*: I used to use `vim-pandoc` when I was writing this colorscheme - so there are some defined highlight groups specific to `vim-pandoc`. However after that I dropped the plugin and didn't miss any functionality or highlighting. Maybe vim improved it's rmarkdown highligh syntax since then.

**Comment by przmv** [comment]
Sure, here's the screenshot!

![distilled-vim-conceal-bug](https://user-images.githubusercontent.com/290451/58423777-997ffa00-809e-11e9-8643-0f368892ff78.png)

**Comment by karoliskoncevicius** [comment]
This was actually a small bug - I should have cleared the `Conceal` group before linking it to `Comment`.

Should be fixed now and linked to `SpecialComment`. Let me know if it suits you.

Here is the commit: https://github.com/KKPMW/distilled-vim/commit/6fd43ffd99dba46e60d2f7e83ff5d07f62421320

Thank you for raising the issue!

**Comment by przmv** [comment]
LGTM! Thanks!
